// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: imgvalidation/v1/img_validation.proto

package imgvalidationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateImageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ImageData       []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ContentTypeHint string                 `protobuf:"bytes,2,opt,name=content_type_hint,json=contentTypeHint,proto3" json:"content_type_hint,omitempty"`
	Purpose         string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	ReferenceId     string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateImageRequest) Reset() {
	*x = ValidateImageRequest{}
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateImageRequest) ProtoMessage() {}

func (x *ValidateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateImageRequest.ProtoReflect.Descriptor instead.
func (*ValidateImageRequest) Descriptor() ([]byte, []int) {
	return file_imgvalidation_v1_img_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ValidateImageRequest) GetContentTypeHint() string {
	if x != nil {
		return x.ContentTypeHint
	}
	return ""
}

func (x *ValidateImageRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ValidateImageRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type ValidateImageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Passed           bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	NsfwScore        float64                `protobuf:"fixed64,2,opt,name=nsfw_score,json=nsfwScore,proto3" json:"nsfw_score,omitempty"`
	FormatValid      bool                   `protobuf:"varint,3,opt,name=format_valid,json=formatValid,proto3" json:"format_valid,omitempty"`
	DetectedMimeType string                 `protobuf:"bytes,4,opt,name=detected_mime_type,json=detectedMimeType,proto3" json:"detected_mime_type,omitempty"`
	Width            int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	SizeBytes        int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	RejectionReasons []string               `protobuf:"bytes,8,rep,name=rejection_reasons,json=rejectionReasons,proto3" json:"rejection_reasons,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateImageResponse) Reset() {
	*x = ValidateImageResponse{}
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateImageResponse) ProtoMessage() {}

func (x *ValidateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateImageResponse.ProtoReflect.Descriptor instead.
func (*ValidateImageResponse) Descriptor() ([]byte, []int) {
	return file_imgvalidation_v1_img_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateImageResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ValidateImageResponse) GetNsfwScore() float64 {
	if x != nil {
		return x.NsfwScore
	}
	return 0
}

func (x *ValidateImageResponse) GetFormatValid() bool {
	if x != nil {
		return x.FormatValid
	}
	return false
}

func (x *ValidateImageResponse) GetDetectedMimeType() string {
	if x != nil {
		return x.DetectedMimeType
	}
	return ""
}

func (x *ValidateImageResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ValidateImageResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ValidateImageResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ValidateImageResponse) GetRejectionReasons() []string {
	if x != nil {
		return x.RejectionReasons
	}
	return nil
}

var File_imgvalidation_v1_img_validation_proto protoreflect.FileDescriptor

const file_imgvalidation_v1_img_validation_proto_rawDesc = "" +
	"\n" +
	"%imgvalidation/v1/img_validation.proto\x12\x10imgvalidation.v1\"\x9e\x01\n" +
	"\x14ValidateImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12*\n" +
	"\x11content_type_hint\x18\x02 \x01(\tR\x0fcontentTypeHint\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\"\x99\x02\n" +
	"\x15ValidateImageResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x1d\n" +
	"\n" +
	"nsfw_score\x18\x02 \x01(\x01R\tnsfwScore\x12!\n" +
	"\fformat_valid\x18\x03 \x01(\bR\vformatValid\x12,\n" +
	"\x12detected_mime_type\x18\x04 \x01(\tR\x10detectedMimeType\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12+\n" +
	"\x11rejection_reasons\x18\b \x03(\tR\x10rejectionReasons2z\n" +
	"\x16ImageValidationService\x12`\n" +
	"\rValidateImage\x12&.imgvalidation.v1.ValidateImageRequest\x1a'.imgvalidation.v1.ValidateImageResponseBJZHimg-validation-service/internal/grpc/pb/imgvalidation/v1;imgvalidationv1b\x06proto3"

var (
	file_imgvalidation_v1_img_validation_proto_rawDescOnce sync.Once
	file_imgvalidation_v1_img_validation_proto_rawDescData []byte
)

func file_imgvalidation_v1_img_validation_proto_rawDescGZIP() []byte {
	file_imgvalidation_v1_img_validation_proto_rawDescOnce.Do(func() {
		file_imgvalidation_v1_img_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imgvalidation_v1_img_validation_proto_rawDesc), len(file_imgvalidation_v1_img_validation_proto_rawDesc)))
	})
	return file_imgvalidation_v1_img_validation_proto_rawDescData
}

var file_imgvalidation_v1_img_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_imgvalidation_v1_img_validation_proto_goTypes = []any{
	(*ValidateImageRequest)(nil),  // 0: imgvalidation.v1.ValidateImageRequest
	(*ValidateImageResponse)(nil), // 1: imgvalidation.v1.ValidateImageResponse
}
var file_imgvalidation_v1_img_validation_proto_depIdxs = []int32{
	0, // 0: imgvalidation.v1.ImageValidationService.ValidateImage:input_type -> imgvalidation.v1.ValidateImageRequest
	1, // 1: imgvalidation.v1.ImageValidationService.ValidateImage:output_type -> imgvalidation.v1.ValidateImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_imgvalidation_v1_img_validation_proto_init() }
func file_imgvalidation_v1_img_validation_proto_init() {
	if File_imgvalidation_v1_img_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imgvalidation_v1_img_validation_proto_rawDesc), len(file_imgvalidation_v1_img_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imgvalidation_v1_img_validation_proto_goTypes,
		DependencyIndexes: file_imgvalidation_v1_img_validation_proto_depIdxs,
		MessageInfos:      file_imgvalidation_v1_img_validation_proto_msgTypes,
	}.Build()
	File_imgvalidation_v1_img_validation_proto = out.File
	file_imgvalidation_v1_img_validation_proto_goTypes = nil
	file_imgvalidation_v1_img_validation_proto_depIdxs = nil
}
