// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: imgvalidation/v1/img_validation.proto

package imgvalidationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateImageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ImageData       []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ContentTypeHint string                 `protobuf:"bytes,2,opt,name=content_type_hint,json=contentTypeHint,proto3" json:"content_type_hint,omitempty"`
	Purpose         string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	ReferenceId     string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateImageRequest) Reset() {
	*x = ValidateImageRequest{}
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateImageRequest) ProtoMessage() {}

func (x *ValidateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateImageRequest.ProtoReflect.Descriptor instead.
func (*ValidateImageRequest) Descriptor() ([]byte, []int) {
	return file_imgvalidation_v1_img_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ValidateImageRequest) GetContentTypeHint() string {
	if x != nil {
		return x.ContentTypeHint
	}
	return ""
}

func (x *ValidateImageRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ValidateImageRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type ValidateImageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Passed           bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	NsfwScore        float64                `protobuf:"fixed64,2,opt,name=nsfw_score,json=nsfwScore,proto3" json:"nsfw_score,omitempty"`
	FormatValid      bool                   `protobuf:"varint,3,opt,name=format_valid,json=formatValid,proto3" json:"format_valid,omitempty"`
	DetectedMimeType string                 `protobuf:"bytes,4,opt,name=detected_mime_type,json=detectedMimeType,proto3" json:"detected_mime_type,omitempty"`
	Width            int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	SizeBytes        int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	RejectionReasons []string               `protobuf:"bytes,8,rep,name=rejection_reasons,json=rejectionReasons,proto3" json:"rejection_reasons,omitempty"`
	FaceCount        int32                  `protobuf:"varint,9,opt,name=face_count,json=faceCount,proto3" json:"face_count,omitempty"`
	FaceConfidence   float64                `protobuf:"fixed64,10,opt,name=face_confidence,json=faceConfidence,proto3" json:"face_confidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateImageResponse) Reset() {
	*x = ValidateImageResponse{}
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateImageResponse) ProtoMessage() {}

func (x *ValidateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateImageResponse.ProtoReflect.Descriptor instead.
func (*ValidateImageResponse) Descriptor() ([]byte, []int) {
	return file_imgvalidation_v1_img_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateImageResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ValidateImageResponse) GetNsfwScore() float64 {
	if x != nil {
		return x.NsfwScore
	}
	return 0
}

func (x *ValidateImageResponse) GetFormatValid() bool {
	if x != nil {
		return x.FormatValid
	}
	return false
}

func (x *ValidateImageResponse) GetDetectedMimeType() string {
	if x != nil {
		return x.DetectedMimeType
	}
	return ""
}

func (x *ValidateImageResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ValidateImageResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ValidateImageResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ValidateImageResponse) GetRejectionReasons() []string {
	if x != nil {
		return x.RejectionReasons
	}
	return nil
}

func (x *ValidateImageResponse) GetFaceCount() int32 {
	if x != nil {
		return x.FaceCount
	}
	return 0
}

func (x *ValidateImageResponse) GetFaceConfidence() float64 {
	if x != nil {
		return x.FaceConfidence
	}
	return 0
}

// MatchFacesRequest compares the face in source_image (selfie) against target_image
// (a profile photo) and returns a cosine-similarity based match score.
type MatchFacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceImage   []byte                 `protobuf:"bytes,1,opt,name=source_image,json=sourceImage,proto3" json:"source_image,omitempty"`
	TargetImage   []byte                 `protobuf:"bytes,2,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFacesRequest) Reset() {
	*x = MatchFacesRequest{}
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFacesRequest) ProtoMessage() {}

func (x *MatchFacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFacesRequest.ProtoReflect.Descriptor instead.
func (*MatchFacesRequest) Descriptor() ([]byte, []int) {
	return file_imgvalidation_v1_img_validation_proto_rawDescGZIP(), []int{2}
}

func (x *MatchFacesRequest) GetSourceImage() []byte {
	if x != nil {
		return x.SourceImage
	}
	return nil
}

func (x *MatchFacesRequest) GetTargetImage() []byte {
	if x != nil {
		return x.TargetImage
	}
	return nil
}

func (x *MatchFacesRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type MatchFacesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Matched         bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Similarity      float64                `protobuf:"fixed64,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
	SourceFaceCount int32                  `protobuf:"varint,3,opt,name=source_face_count,json=sourceFaceCount,proto3" json:"source_face_count,omitempty"`
	TargetFaceCount int32                  `protobuf:"varint,4,opt,name=target_face_count,json=targetFaceCount,proto3" json:"target_face_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchFacesResponse) Reset() {
	*x = MatchFacesResponse{}
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFacesResponse) ProtoMessage() {}

func (x *MatchFacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFacesResponse.ProtoReflect.Descriptor instead.
func (*MatchFacesResponse) Descriptor() ([]byte, []int) {
	return file_imgvalidation_v1_img_validation_proto_rawDescGZIP(), []int{3}
}

func (x *MatchFacesResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *MatchFacesResponse) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *MatchFacesResponse) GetSourceFaceCount() int32 {
	if x != nil {
		return x.SourceFaceCount
	}
	return 0
}

func (x *MatchFacesResponse) GetTargetFaceCount() int32 {
	if x != nil {
		return x.TargetFaceCount
	}
	return 0
}

// CheckLivenessRequest runs anti-spoof (presentation attack detection) on a single frame.
type CheckLivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLivenessRequest) Reset() {
	*x = CheckLivenessRequest{}
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLivenessRequest) ProtoMessage() {}

func (x *CheckLivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLivenessRequest.ProtoReflect.Descriptor instead.
func (*CheckLivenessRequest) Descriptor() ([]byte, []int) {
	return file_imgvalidation_v1_img_validation_proto_rawDescGZIP(), []int{4}
}

func (x *CheckLivenessRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *CheckLivenessRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type CheckLivenessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Live          bool                   `protobuf:"varint,1,opt,name=live,proto3" json:"live,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLivenessResponse) Reset() {
	*x = CheckLivenessResponse{}
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLivenessResponse) ProtoMessage() {}

func (x *CheckLivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imgvalidation_v1_img_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLivenessResponse.ProtoReflect.Descriptor instead.
func (*CheckLivenessResponse) Descriptor() ([]byte, []int) {
	return file_imgvalidation_v1_img_validation_proto_rawDescGZIP(), []int{5}
}

func (x *CheckLivenessResponse) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *CheckLivenessResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_imgvalidation_v1_img_validation_proto protoreflect.FileDescriptor

const file_imgvalidation_v1_img_validation_proto_rawDesc = "" +
	"\n" +
	"%imgvalidation/v1/img_validation.proto\x12\x10imgvalidation.v1\"\x9e\x01\n" +
	"\x14ValidateImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12*\n" +
	"\x11content_type_hint\x18\x02 \x01(\tR\x0fcontentTypeHint\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\"\xe1\x02\n" +
	"\x15ValidateImageResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x1d\n" +
	"\n" +
	"nsfw_score\x18\x02 \x01(\x01R\tnsfwScore\x12!\n" +
	"\fformat_valid\x18\x03 \x01(\bR\vformatValid\x12,\n" +
	"\x12detected_mime_type\x18\x04 \x01(\tR\x10detectedMimeType\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12+\n" +
	"\x11rejection_reasons\x18\b \x03(\tR\x10rejectionReasons\x12\x1d\n" +
	"\n" +
	"face_count\x18\t \x01(\x05R\tfaceCount\x12'\n" +
	"\x0fface_confidence\x18\n" +
	" \x01(\x01R\x0efaceConfidence\"|\n" +
	"\x11MatchFacesRequest\x12!\n" +
	"\fsource_image\x18\x01 \x01(\fR\vsourceImage\x12!\n" +
	"\ftarget_image\x18\x02 \x01(\fR\vtargetImage\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\"\xa6\x01\n" +
	"\x12MatchFacesResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x01R\n" +
	"similarity\x12*\n" +
	"\x11source_face_count\x18\x03 \x01(\x05R\x0fsourceFaceCount\x12*\n" +
	"\x11target_face_count\x18\x04 \x01(\x05R\x0ftargetFaceCount\"X\n" +
	"\x14CheckLivenessRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12!\n" +
	"\freference_id\x18\x02 \x01(\tR\vreferenceId\"A\n" +
	"\x15CheckLivenessResponse\x12\x12\n" +
	"\x04live\x18\x01 \x01(\bR\x04live\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score2\xb5\x02\n" +
	"\x16ImageValidationService\x12`\n" +
	"\rValidateImage\x12&.imgvalidation.v1.ValidateImageRequest\x1a'.imgvalidation.v1.ValidateImageResponse\x12W\n" +
	"\n" +
	"MatchFaces\x12#.imgvalidation.v1.MatchFacesRequest\x1a$.imgvalidation.v1.MatchFacesResponse\x12`\n" +
	"\rCheckLiveness\x12&.imgvalidation.v1.CheckLivenessRequest\x1a'.imgvalidation.v1.CheckLivenessResponseBJZHimg-validation-service/internal/grpc/pb/imgvalidation/v1;imgvalidationv1b\x06proto3"

var (
	file_imgvalidation_v1_img_validation_proto_rawDescOnce sync.Once
	file_imgvalidation_v1_img_validation_proto_rawDescData []byte
)

func file_imgvalidation_v1_img_validation_proto_rawDescGZIP() []byte {
	file_imgvalidation_v1_img_validation_proto_rawDescOnce.Do(func() {
		file_imgvalidation_v1_img_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imgvalidation_v1_img_validation_proto_rawDesc), len(file_imgvalidation_v1_img_validation_proto_rawDesc)))
	})
	return file_imgvalidation_v1_img_validation_proto_rawDescData
}

var file_imgvalidation_v1_img_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_imgvalidation_v1_img_validation_proto_goTypes = []any{
	(*ValidateImageRequest)(nil),  // 0: imgvalidation.v1.ValidateImageRequest
	(*ValidateImageResponse)(nil), // 1: imgvalidation.v1.ValidateImageResponse
	(*MatchFacesRequest)(nil),     // 2: imgvalidation.v1.MatchFacesRequest
	(*MatchFacesResponse)(nil),    // 3: imgvalidation.v1.MatchFacesResponse
	(*CheckLivenessRequest)(nil),  // 4: imgvalidation.v1.CheckLivenessRequest
	(*CheckLivenessResponse)(nil), // 5: imgvalidation.v1.CheckLivenessResponse
}
var file_imgvalidation_v1_img_validation_proto_depIdxs = []int32{
	0, // 0: imgvalidation.v1.ImageValidationService.ValidateImage:input_type -> imgvalidation.v1.ValidateImageRequest
	2, // 1: imgvalidation.v1.ImageValidationService.MatchFaces:input_type -> imgvalidation.v1.MatchFacesRequest
	4, // 2: imgvalidation.v1.ImageValidationService.CheckLiveness:input_type -> imgvalidation.v1.CheckLivenessRequest
	1, // 3: imgvalidation.v1.ImageValidationService.ValidateImage:output_type -> imgvalidation.v1.ValidateImageResponse
	3, // 4: imgvalidation.v1.ImageValidationService.MatchFaces:output_type -> imgvalidation.v1.MatchFacesResponse
	5, // 5: imgvalidation.v1.ImageValidationService.CheckLiveness:output_type -> imgvalidation.v1.CheckLivenessResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_imgvalidation_v1_img_validation_proto_init() }
func file_imgvalidation_v1_img_validation_proto_init() {
	if File_imgvalidation_v1_img_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imgvalidation_v1_img_validation_proto_rawDesc), len(file_imgvalidation_v1_img_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imgvalidation_v1_img_validation_proto_goTypes,
		DependencyIndexes: file_imgvalidation_v1_img_validation_proto_depIdxs,
		MessageInfos:      file_imgvalidation_v1_img_validation_proto_msgTypes,
	}.Build()
	File_imgvalidation_v1_img_validation_proto = out.File
	file_imgvalidation_v1_img_validation_proto_goTypes = nil
	file_imgvalidation_v1_img_validation_proto_depIdxs = nil
}
