// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: imgvalidation/v1/img_validation.proto

package imgvalidationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageValidationService_ValidateImage_FullMethodName = "/imgvalidation.v1.ImageValidationService/ValidateImage"
)

// ImageValidationServiceClient is the client API for ImageValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageValidationServiceClient interface {
	ValidateImage(ctx context.Context, in *ValidateImageRequest, opts ...grpc.CallOption) (*ValidateImageResponse, error)
}

type imageValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageValidationServiceClient(cc grpc.ClientConnInterface) ImageValidationServiceClient {
	return &imageValidationServiceClient{cc}
}

func (c *imageValidationServiceClient) ValidateImage(ctx context.Context, in *ValidateImageRequest, opts ...grpc.CallOption) (*ValidateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateImageResponse)
	err := c.cc.Invoke(ctx, ImageValidationService_ValidateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageValidationServiceServer is the server API for ImageValidationService service.
// All implementations must embed UnimplementedImageValidationServiceServer
// for forward compatibility.
type ImageValidationServiceServer interface {
	ValidateImage(context.Context, *ValidateImageRequest) (*ValidateImageResponse, error)
	mustEmbedUnimplementedImageValidationServiceServer()
}

// UnimplementedImageValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageValidationServiceServer struct{}

func (UnimplementedImageValidationServiceServer) ValidateImage(context.Context, *ValidateImageRequest) (*ValidateImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateImage not implemented")
}
func (UnimplementedImageValidationServiceServer) mustEmbedUnimplementedImageValidationServiceServer() {
}
func (UnimplementedImageValidationServiceServer) testEmbeddedByValue() {}

// UnsafeImageValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageValidationServiceServer will
// result in compilation errors.
type UnsafeImageValidationServiceServer interface {
	mustEmbedUnimplementedImageValidationServiceServer()
}

func RegisterImageValidationServiceServer(s grpc.ServiceRegistrar, srv ImageValidationServiceServer) {
	// If the following call pancis, it indicates UnimplementedImageValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageValidationService_ServiceDesc, srv)
}

func _ImageValidationService_ValidateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageValidationServiceServer).ValidateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageValidationService_ValidateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageValidationServiceServer).ValidateImage(ctx, req.(*ValidateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageValidationService_ServiceDesc is the grpc.ServiceDesc for ImageValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imgvalidation.v1.ImageValidationService",
	HandlerType: (*ImageValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateImage",
			Handler:    _ImageValidationService_ValidateImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imgvalidation/v1/img_validation.proto",
}
